#!/usr/bin/env node

var resolve = require('path').resolve
  , glagol  = require('glagol')
  , server  = glagol(resolve(__dirname, 'server'));

server.bind(glagol(resolve(__dirname, 'common')));

server().main();
